config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'twilio#new'

  resources :twilio, only: %i[new create] do
    collection do
      get 'connect'
      post 'connect'
    end
  end

  resources :twilio_sms, only: %i[new create] do
    collection do
      post 'verify_code'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def verify_user(code)
    return false unless code == verification_code

    update(verified: true, enable_sms: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session, prepend: true
end

app/controllers/concerns/verification_code_generator.rb
module VerificationCodeGenerator
  def generate_code(length)
    length += 2
    rand.to_s[2..length]
  end
end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController
  before_action :permit_params, only: :create
  before_action :authenticate_twilio_request, only: :connect

  def new
    respond_to do |format|
      format.html
    end
  end

  def create
    TwilioAPI.call_number(params[:number_from], params[:number_to])
    flash[:notice] = t(:twilio_call_success, number: params[:number_from])

    respond_to do |format|
      format.js
    end
  end

  def connect
    response = TwilioAPI.call_forwarding_response(params[:number_to])
    render(xml: response.to_s)
  end

  private

  def permit_params
    params.permit(:number_from, :number_to)
  end

  def authenticate_twilio_request
    return true if TwilioAPI.twilio_req?(request, params)

    response = TwilioAPI.hangup_response

    render xml: response.to_s, status: :unauthorized
    false
  end
end

app/controllers/twilio_sms_controller.rb
# App/Controllers/TwilioSmsController
class TwilioSmsController < ApplicationController
  include VerificationCodeGenerator
  before_action :set_user

  def new
    respond_to do |format|
      format.html
    end
  end

  def create
    verification_code = generate_code(DEFAULT_VERIFICATION_CODE_LENGTH)
    message_body      = "Your verification code is #{verification_code}"

    TwilioAPI.send_message(params[:user_number], message_body)
    @user.update(verification_code: verification_code, phone_number: params[:user_number])
    flash[:notice] = t(:twilio_sms_sent, number: params[:user_number])

    respond_to do |format|
      format.js
    end
  end

  def verify_code
    if @user.verify_user(params[:verification_code])
      flash[:notice] = t(:twilio_user_verified)
    else
      flash[:error] = t(:twilio_verification_failed)
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.permit(:verification_code, :phone_number)
  end

  def set_user
    @user = User.all.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title><%= APP_NAME %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <%= yield :stylesheets %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="hold-transition layout-top-nav">
    <div class="wrapper">
      <!-- Navbar -->
      <%= render 'shared/top_nav' %>
      <!-- /.navbar -->
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1 class="m-0 text-dark"><%= yield :page_header %></h1>
              </div><!-- /.col -->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
          <div class="container">
            <div id="flash_messages">
              <% if flash[:notice].present? %>
                <%= render 'shared/flash_notice' %>
              <% end %>

              <% if flash[:error].present? %>
                <%= render 'shared/flash_error' %>
              <% end %>
            </div>
            <%= yield %>
          </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
      </div>

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
          Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
      </footer>
    </div>

    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <%= yield :javascripts %>
  </body>
</html>

app/views/shared/_flash_error.html.erb
<div class="alert alert-danger alert-dismissible">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h5><i class="icon fas fa-ban"></i> Error!</h5>
  <%= flash[:error] %>
</div>

app/views/shared/_flash_notice.html.erb
<div class="alert alert-success alert-dismissible">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <h5><i class="icon fas fa-check"></i> Success!</h5>
  <%= flash[:notice] %>
</div>

app/views/shared/_top_nav.html.erb
<nav class="main-header navbar navbar-expand navbar-light navbar-white">
  <div class="container">
    <a href="index3.html" class="navbar-brand">
      <img src="/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
          style="opacity: .8">
      <span class="brand-text font-weight-light"><%= APP_NAME %></span>
    </a>

    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
      </li>
      <li class="nav-item d-none d-sm-inline-block <%= controller_name == 'twilio' ? 'active' : '' %>">
        <a href="<%= root_path %>" class="nav-link">Call Manager</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block <%= controller_name == 'twilio_sms' ? 'active' : '' %>">
        <a href="<%= new_twilio_sm_path %>" class="nav-link">SMS Manager</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
    </ul>
  </div>
</nav>

app/views/twilio/create.js.erb
window.scrollTo(0, 0);
<% if flash[:error].present? %>
  $('#flash_messages').html("<%= escape_javascript(render('shared/flash_error')) %>")
  <% flash[:error] = nil %>
<% elsif flash[:notice].present? %>
  $('#flash_messages').html("<%= escape_javascript(render('shared/flash_notice')) %>")
  <% flash[:notice] = nil %>
<% end %>

app/views/twilio/new.html.erb
<% content_for :page_header do %>
  Twilio Call Manager
<% end %>
<div class="row">
  <div class="col-lg-12">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Fill Numbers</h3>
      </div>
      <%= form_tag twilio_index_path, role: 'form', remote: true do |f| %>
        <div class="card-body">
          <div class="form-group col-6">
            <%= label_tag :from %>
            <%= text_field_tag :number_from, '', required: true, class: 'form-control', placeholder: '(651) 555-7889' %>
          </div>

          <div class="form-group col-6">
            <%= label_tag :to %>
            <%= text_field_tag :number_to, '', required: true, class: 'form-control', placeholder: '(651) 555-7889' %>
          </div>
        </div>
        <div class="card-footer">
          <%= submit_tag 'Call', class: 'btn btn-primary', data: { disable_with: "Submitting..." } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/twilio_sms/_user_number_form.html.erb
<%= form_tag twilio_sms_path, role: 'form', remote: true do |f| %>
  <div class="card-body">
    <div class="form-group col-6">
      <%= label_tag :user_number %>
      <%= text_field_tag :user_number, '', required: true, class: 'form-control', placeholder: '(651) 555-7889' %>
    </div>
  </div>
  <div class="card-footer">
    <%= submit_tag 'Verify', class: 'btn btn-primary', data: { disable_with: "Sending verification code..." } %>
  </div>
<% end %>

app/views/twilio_sms/_verification_success.html.erb
<div class="card-body">
  <div class="form-group col-6">
    <p>User verified!</p>
  </div>
</div>

app/views/twilio_sms/_verify_number_form.html.erb
<%= form_tag verify_code_twilio_sms_path, role: 'form', remote: true do |f| %>
  <div class="card-body">
    <div class="form-group col-6">
      <%= label_tag :verification_code %>
      <%= text_field_tag :verification_code, '', required: true, class: 'form-control', placeholder: 'xxxxxx' %>
    </div>
  </div>
  <div class="card-footer">
    <%= submit_tag 'Verify', class: 'btn btn-primary', data: { disable_with: "Sending verification code..." } %>
  </div>
<% end %>

app/views/twilio_sms/create.js.erb
$('#twilio_form').html('<%= escape_javascript(render('verify_number_form')) %>');
$('.card-title').html('Enter 6 digit verification code');

<% if flash[:error].present? %>
  $('#flash_messages').html("<%= escape_javascript(render('shared/flash_error')) %>")
  <% flash[:error] = nil %>
<% elsif flash[:notice].present? %>
  $('#flash_messages').html("<%= escape_javascript(render('shared/flash_notice')) %>")
  <% flash[:notice] = nil %>
<% end %>

app/views/twilio_sms/new.html.erb
<% content_for :page_header do %>
  Twilio SMS Manager
<% end %>
<div class="row">
  <div class="col-lg-12">
    <div class="card card-primary">
      <div class="card-header">
        <h3 class="card-title">Enter Number</h3>
      </div>
      <div id="twilio_form">
        <%= render 'user_number_form' %>
      </div>
    </div>
  </div>
</div>

app/views/twilio_sms/verify_code.js.erb
$('#twilio_form').html('<%= escape_javascript(render('verification_success')) %>')

<% if flash[:error].present? %>
  $('#flash_messages').html("<%= escape_javascript(render('shared/flash_error')) %>")
  <% flash[:error] = nil %>
<% elsif flash[:notice].present? %>
  $('#flash_messages').html("<%= escape_javascript(render('shared/flash_notice')) %>")
  <% flash[:notice] = nil %>
<% end %>